[package]
name = "alloy-rs"
version = "0.2.1"
edition = "2021"

[lib]
crate-type = [ "staticlib" ]

[dependencies]
arrow2 = "0.18.0"
chrono = "0.4.31"
env_logger = "0.10.1"
libc = "0.2.150"
log = "0.4.20"
