name: Rust tests

on:
  pull_request:
    paths:
      - "./alloy-rs/**"
  push:
    branches: [ main ]
    paths:
      - ./alloy-rs

jobs:
  tests:
    name: Unittests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        rust: [ stable ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: llvm-tools-preview
          override: true
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests
        run: |
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
        working-directory: ./alloy-rs
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./alloy-rs/lcov.info
          fail_ci_if_error: true
